<?php
require_once 'includes/config.php';
requireRole('Client');
$client=$pdo->prepare("SELECT client_id FROM clients WHERE user_id=?");$client->execute([$_SESSION['user_id']]);$client_id=$client->fetchColumn();
$cart=$_SESSION['cart'] ?? []; $items=[];$product_total=0;
if($cart){$ids=array_keys($cart);$ph=implode(',',array_fill(0,count($ids),'?'));$st=$pdo->prepare("SELECT * FROM products WHERE product_id IN ($ph)");$st->execute($ids);foreach($st->fetchAll() as $p){$p['qty']=$cart[$p['product_id']];$p['line_total']=$p['qty']*$p['price'];$product_total+=$p['line_total'];$items[]=$p;}}
$bst=$pdo->prepare("SELECT b.booking_id,b.booking_date,b.time_slot,s.service_name,s.price FROM bookings b JOIN services s ON s.service_id=b.service_id LEFT JOIN payments pay ON pay.booking_id=b.booking_id AND pay.status='Paid' WHERE b.client_id=? AND b.status!='Cancelled' AND pay.payment_id IS NULL ORDER BY b.booking_date DESC");$bst->execute([$client_id]);$bookings=$bst->fetchAll();$booking_total=array_sum(array_column($bookings,'price'));$grand=$product_total+$booking_total;
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!$items && !$bookings){setFlash('danger','There is nothing to check out.');redirect('catalog.php');}
 $pdo->beginTransaction();
 try {
  if($items){$st=$pdo->prepare("INSERT INTO orders (client_id,total_amount,status) VALUES (?,?,'Pending')");$st->execute([$client_id,$product_total]);$order_id=$pdo->lastInsertId();$oi=$pdo->prepare("INSERT INTO order_items (order_id,product_id,quantity,unit_price) VALUES (?,?,?,?)");foreach($items as $p)$oi->execute([$order_id,$p['product_id'],$p['qty'],$p['price']]);}
  foreach($bookings as $b){$check=$pdo->prepare("SELECT COUNT(*) FROM payments WHERE booking_id=?");$check->execute([$b['booking_id']]);if(!$check->fetchColumn()){$ins=$pdo->prepare("INSERT INTO payments (booking_id,amount,payment_method,status) VALUES (?,?,'Credit Card','Pending')");$ins->execute([$b['booking_id'],$b['price']]);}}
  $pdo->commit(); $_SESSION['cart']=[]; setFlash('success','Your checkout has been created. Payment gateway integration can now process the pending total.'); redirect('payment.php'.(isset($order_id)?'?order_id='.$order_id:''));
 } catch(Throwable $e){$pdo->rollBack();$error='Could not create your checkout. '.$e->getMessage();}
}
$pageTitle='Checkout';require_once 'includes/header.php'; ?>
<div class="container py-5"><h2>Checkout</h2><?php if(!empty($error)):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?><div class="row"><div class="col-md-8"><div class="card border-0 shadow-sm"><div class="card-body"><h5>Boutique Products</h5><?php foreach($items as $p):?><div class="d-flex justify-content-between border-bottom py-2"><span><?php echo htmlspecialchars($p['name']);?> × <?php echo $p['qty'];?></span><span>R <?php echo number_format($p['line_total'],2);?></span></div><?php endforeach;?><h5 class="mt-4">Booked Services Awaiting Payment</h5><?php foreach($bookings as $b):?><div class="d-flex justify-content-between border-bottom py-2"><span><?php echo htmlspecialchars($b['service_name']);?> — <?php echo $b['booking_date'];?> <?php echo substr($b['time_slot'],0,5);?></span><span>R <?php echo number_format($b['price'],2);?></span></div><?php endforeach;?></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><p>Products: R <?php echo number_format($product_total,2);?></p><p>Services: R <?php echo number_format($booking_total,2);?></p><hr><h4>Total: R <?php echo number_format($grand,2);?></h4><form method="post"><button class="btn btn-malaika w-100 mt-3" <?php echo $grand<=0?'disabled':'';?>>Continue to Payment</button></form></div></div></div></div></div><?php require_once 'includes/footer.php'; ?>